name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: 'api/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make -C api test

    - name: Build
      run: make -C api build
