name: api_deploy

on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Test
      run: make -C api test

    - name: Build
      run: make -C api build

    - name: Bundle
      run : |
          echo "${{ secrets.API_ENV_CONFIG }}" > ${{ github.workspace }}/api/build/env
          cd ${{ github.workspace }}/api; tar -zcvf server.tgz build

    - name: upload server artifact
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: ${{ github.workspace }}/api/build/server

    - name: upload server.tgz artifact
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: ${{ github.workspace }}/api/server.tgz

    - name: trigger new image
      uses: fifsky/ssh-action@master
      with:
        command: sudo /usr/bin/restart_server.sh
        host: ${{ secrets.API_HOST }}
        user: cicd
        key: ${{ secrets.API_PRIVATE_KEY}}
