name: api_deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ api_test ]
    types: [completed]
    branches: [main]
jobs:

  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: trigger new image
      uses: fifsky/ssh-action@master
      with:
        command: sudo /usr/bin/restart_server.sh
        host: ${{ secrets.API_HOST }}
        user: cicd
        key: ${{ secrets.API_PRIVATE_KEY}}
