name: api_deploy

on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Test
      run: make -C api test

    - name: Build
      run: make -C api build

    - name: upload server artifact
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: ${{ github.workspace }}/build/server
