name: twitterlike

on:
  push:
    branches: [ main ]
    paths:
        - 'twitterlike/**'
        - '.github/workflows/twitterlike.yml'
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --silent # will run `yarn install` command
        dir: ${{ github.workspace }}/twitterlike

    - name: Run lint
      uses: borales/actions-yarn@v4
      with:
        cmd: lint
        dir: ${{ github.workspace }}/twitterlike

    - name: Run test
      uses: borales/actions-yarn@v4
      with:
        cmd: citest
        dir: ${{ github.workspace }}/twitterlike

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
        dir: ${{ github.workspace }}/twitterlike
    - name: Bundle
      run : |
          echo "${{ secrets.TWTR_ENV_CONFIG }}" > ${{ github.workspace }}/twitterlike/.env.local
          cd ${{ github.workspace }}; tar -zcf twitter.tgz twitterlike

    - name: upload twitter.tgz artifact
      uses: actions/upload-artifact@v2
      with:
        name: twitter.tgz
        path: ${{ github.workspace }}/twitter.tgz

    - name: trigger new twitter image
      uses: fifsky/ssh-action@master
      with:
        command: sudo /usr/bin/restart_twitter.sh
        host: ${{ secrets.TWTR_HOST }}
        user: cicd
        key: ${{ secrets.TWTR_PRIVATE_KEY}}
